# Generated by Django 3.2.10 on 2022-03-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
